name: Release executable
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build and release executable
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Set up python
        uses: actions/setup-python@v2 
        with:
          python-version: 3.13
      - name: Install build tools
        run: pip install pyinstaller pipenv
      - name: Install dependencies
        run: pipenv install && pipenv shell
      - name: Build
        run: pyinstaller --noconsole --onefile csd_viewer.py
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/csd_viewer.exe
